language: node_js
node_js:
  - "10"
cache: yarn
branches:
  only:
  - master
install:
  - yarn
script:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: 1/QWYKlAZG6WyFhPLsqI3IskgcyPatoTCt3Ks1tw6htl4
  project: cpe-projectregbot-bumgbp