language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - yarn
        - echo 'Prepare Deploy'
    - stage: deploy
      script:
        - npm install -g firebase-tools
        - yarn build
        - firebase deploy
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master