language: node_js
node_js:
  - "10"
cache: yarn
branches:
  only:
  - master
before_script:
  - npm install -g firebase-tools
  - cd functions && npm install 
  - cd ..
install:
  - yarn
script:
  - yarn build
  - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  # --ignore-missing-functions --allow-deletes
